## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [1]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [9]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
df = pd.read_csv("bridge-inspections-excerpt.csv")
df

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [10]:
## call the first 10 rows
df.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [11]:
## call the last 5 rows
df.tail(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99990,53,57,'NOOKACHAMPS CREEK',48254300.0,122153260.0,2.0,9.0,1977.0,5,2.0,6,7,7,7,N,NaN
99991,53,71,'NINE MILE CANYON',46041500.0,118465600.0,2.0,8.0,1916.0,1,0.0,N,5,5,6,N,NaN
99992,53,63,'LITTLE SPOKANE RIVER',47541420.0,117203676.0,2.0,9.0,1984.0,5,2.0,7,7,7,8,N,NaN
99993,53,77,'ROZA CANAL',46360246.0,120252046.0,2.0,16.0,1967.0,5,2.0,7,7,6,6,N,NaN
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [13]:
## call a 20 random rows
df.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
22517,48,405,'AYISH BAYOU',31210242.0,94082765.0,2.0,9.0,2021.0,5,5.0,9,9,8,7,N,NaN
66857,48,85,'DALLAS NORTH TOLLWAY',33062438.0,96492268.0,NaN,12.0,2011.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
67552,48,113,'IH 30 WB',32460276.0,96514534.0,NaN,19.0,2006.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
9867,48,9,'DRAW',33462730.0,98411448.0,1.0,7.0,1951.0,1,19.0,N,N,N,8,5,NaN
7822,48,439,'Overton Ridge',32403688.0,97242496.0,1.0,12.0,2013.0,5,2.0,7,8,8,N,N,NaN
66367,48,355,'S.CROSSOVER / ON-RAMP',NaN,NaN,NaN,12.0,2004.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71279,49,7,'PRICE RIVER',39413120.0,110512448.0,4.0,17.0,1976.0,5,2.0,5,7,6,6,N,NaN
41176,48,355,'DRAINAGE DITCH',27462410.0,97401930.0,1.0,1.0,2011.0,1,19.0,N,N,N,6,7,NaN
6693,48,367,'GOURDNECK CREEK',32544464.0,97513400.0,1.0,7.0,1957.0,1,19.0,N,N,N,7,7,NaN
63129,48,201,'SH 249',29535357.0,95244377.0,NaN,14.0,1989.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
43589,48,471,'POLECAT BRANCH',30375064.0,95421600.0,1.0,7.0,1955.0,1,1.0,7,7,5,5,N,NaN
93438,51,153,'ROUTE 95 S.B.L.',38401709.0,77145605.0,NaN,1.0,1996.0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71638,49,1,'BEAVER RIVER',38155378.0,112390046.0,1.0,1.0,1970.0,5,2.0,6,6,7,6,N,NaN
70847,49,3,'BEAR RIVER',41424800.0,112070200.0,1.0,7.0,1953.0,2,7.0,7,7,6,7,N,1.0
41760,48,409,'DRAW',27592575.0,97413090.0,1.0,7.0,1970.0,1,19.0,N,N,N,7,7,NaN
10055,48,77,'WICHITA RIVER',34032295.0,98174217.0,1.0,7.0,1955.0,4,2.0,6,6,6,6,N,NaN
42112,48,41,'BRAZOS RIVER',30333280.0,96252434.0,1.0,6.0,2000.0,5,2.0,7,7,7,5,N,1.0
69082,48,489,'SPUR 112',26244322.0,97470654.0,NaN,8.0,2003.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
58822,48,125,'DRAW',33370109.0,100395847.0,1.0,2.0,1936.0,1,19.0,N,N,N,7,6,NaN
29503,48,15,'LITTLE BERNARD CREEK',29470334.0,96123877.0,1.0,7.0,1965.0,1,2.0,6,6,7,7,N,NaN

In [14]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate?

In [15]:
## call the top 7 rows
df.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [16]:
## call a sample of 10
df.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
18866,48,293,'SALT CRK #40',31424294.0,96264402.0,2.0,9.0,1993.0,1,2.0,7,7,7,6,N,NaN
54804,48,489,'W HARGILL DRAIN DITCH',26285545.0,97584731.0,2.0,9.0,1974.0,1,2.0,6,6,5,6,N,NaN
93960,51,139,'ROUTE 683 & NS RAILWAY',38302236.0,78373024.0,NaN,9.0,2004.0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN
38461,48,29,'ELM CREEK',29352779.0,98255548.0,4.0,19.0,1980.0,3,19.0,N,N,N,7,6,NaN
12674,48,135,'BI 20 E W-E Turnaround',31520882.0,102191242.0,1.0,14.0,2009.0,5,2.0,6,8,7,N,N,NaN
13063,48,371,'DRAW',30521690.0,102363181.0,1.0,1.0,1975.0,1,19.0,N,N,N,8,7,NaN
47120,48,113,'LAKE RAY HUBBARD',32533018.0,96322474.0,4.0,16.0,1969.0,1,2.0,7,7,5,5,N,1.0
9838,48,9,'DRAW',33475261.0,98285935.0,1.0,6.0,1929.0,1,19.0,N,N,N,7,6,NaN
59321,48,345,'MIDDLE PEASE RIVER',34063338.0,100455476.0,1.0,7.0,2008.0,5,2.0,6,8,7,8,N,NaN
96619,53,15,'C&C RY & COUNTY RD',46103270.0,122541110.0,1.0,11.0,1976.0,6,2.0,6,7,7,N,N,NaN

In [17]:
## call the bottom 6
df.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [21]:
## call the year built column using dot notation
df.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [23]:
## call FEATURES_DESC_006A as a series using square bracket notation

df["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [26]:
## what are the unique owner codes?
df.OWNER_022.unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

In [ ]:
I don't know the significance of the numbers